theme = "relearn"

baseURL = "https://pegel-konstanz.de/"

title = "Pegel Konstanz - Bodensee"
description = "Aktuelle und historische Informationen zum Pegel des Bodensees"

# German is the default language
defaultContentLanguage = "de"

# create robots.txt
enableRobotsTXT = false

[languages]
[languages.de]
title = "Aktuelle und historische Informationen zum Pegel des Bodensees"
weight = 1
languageName = "Deutsch"

[languages.en]
title = "Current and historical information on the level of Lake Constance"
weight = 2
languageName = "English"

[outputs]
home = [ "HTML", "RSS"]

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Mastodon"
url = "https://mastodon.social/@pegelkonstanz"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
url = "https://github.com/davidbeckonline/pegel-konstanz"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> HVZ LUBW"
url = "https://www.hvz.baden-wuerttemberg.de/pegel.html?id=00007"
weight = 30


[markup]
  [markup.goldmark.renderer]
    # activated for this showcase to use HTML and JavaScript; decide on your own needs;
    # if in doubt, remove this line
    unsafe = true
  
[params]
  themeVariant = ["mine"]
  search = false
  hideAuthorDate = true

